### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/FDO-support#16]
This is a placeholder until we post more details.  The intent is to put appropriate issue templates so that issues opened in this repo are similar to anax and other repos.  That will either involve creating issue templates under /.github in this repo, or even better, identifying templates that apply to all repos and posting those in the .github repo.

**Comment by joewxboy** [comment]
# GitHub Issue and PR Templates Implementation Plan

## Executive Summary

This document outlines the plan for implementing GitHub issue and pull request templates for the FDO-support repository, based on analysis of existing templates in the `open-horizon/anax` and `open-horizon/open-horizon.github.io` repositories.

## Current State Analysis

### Templates in open-horizon/anax Repository

The anax repository uses **YAML-based issue templates** (GitHub's modern form-based approach):

1. **bug-report.yml** - Structured bug reporting with required fields
2. **feature_request.yml** - Feature suggestions with problem/solution format
3. **documentation-update.yml** - Documentation improvement requests
4. **new-arch.yml** - New microprocessor architecture support (project-specific)
5. **new-distro.yml** - New Linux distribution support (project-specific)
6. **user-feedback.yml** - General user feedback
7. **Other.md** - Catch-all for issues not fitting other categories
8. **PULL_REQUEST_TEMPLATE.md** - Comprehensive PR checklist

### Templates in open-horizon.github.io Repository

- Uses similar structure with ISSUE_TEMPLATE directory
- Has PULL_REQUEST_TEMPLATE.md
- Includes config.yml for GitHub configuration

## Recommended Templates for FDO-support

### Priority 1: Essential Templates (Implement First)

#### 1. Bug Report Template
**Rationale**: Critical for tracking issues with FDO integration, OCS API, and Docker services.

**Customizations for FDO-support**:
- Add FDO-specific fields:
  - FDO version (FIDO_DEVICE_ONBOARD_REL_VER)
  - Component affected (OCS API, Owner Services, Manufacturing, Rendezvous)
  - Device type (physical FDO device, VM simulation)
  - Exchange/CSS connectivity status
- Include environment details:
  - Docker version
  - Go version
  - Operating system (for OCS API development)
  - Management hub configuration

#### 2. Feature Request Template
**Rationale**: Allows community to suggest improvements to FDO integration.

**Customizations for FDO-support**:
- Add context about:
  - Which FDO protocol phase (TO0, TO1, TO2)
  - Integration point (Exchange, CSS, agent-install)
  - Use case (manufacturing, deployment, management)

#### 3. Pull Request Template
**Rationale**: Ensures code quality and proper review process.

**Customizations for FDO-support**:
- Add FDO-specific checklist items:
  - [ ] Tested with actual FDO devices or VM simulation
  - [ ] Updated FDO version compatibility documentation
  - [ ] Verified Exchange authentication still works
  - [ ] Tested with both HTTP and HTTPS configurations
  - [ ] Updated API documentation if endpoints changed
  - [ ] Verified Docker image builds successfully
  - [ ] Tested voucher import/export workflow
  - [ ] Checked compatibility with current FDO specification version

### Priority 2: Recommended Templates (Implement Second)

#### 4. Documentation Update Template
**Rationale**: FDO-support has extensive documentation that needs maintenance.

**Customizations for FDO-support**:
- Focus areas:
  - API documentation (docs/FDO-APIs.md)
  - Usage guides (docs/README-FDO.md)
  - AGENTS.md updates
  - Sample script documentation

#### 5. Integration Issue Template
**Rationale**: FDO-support is an integration project between FDO and Open Horizon.

**New template specific to FDO-support**:
```yaml
name: Integration Issue
description: Report issues with FDO and Open Horizon integration
title: "Integration: "
labels: [integration, bug]

body:
  - type: markdown
    attributes:
      value: Thank you for reporting an integration issue between FDO and Open Horizon.
  
  - type: dropdown
    attributes:
      label: Integration Component
      description: Which component is experiencing the integration issue?
      options:
        - Exchange Authentication
        - CSS File Management
        - Agent Installation
        - Voucher Management
        - Certificate Handling
        - Service Info Package
        - Other
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Describe the integration issue
      description: What is not working between FDO and Open Horizon?
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: FDO Environment Details
      description: |
        Please provide:
        - FDO version (FIDO_DEVICE_ONBOARD_REL_VER)
        - Open Horizon version
        - Exchange URL and accessibility
        - CSS URL and accessibility
      placeholder: |
        FDO Version: 1.1.10
        Horizon Version: 2.30.0
        Exchange: https://exchange.example.com (accessible)
        CSS: https://css.example.com (accessible)
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this integration issue?
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should happen in a successful integration?
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Logs and Error Messages
      description: Please include relevant logs from OCS API, Docker containers, or device
      placeholder: |
        Paste logs here...
```

### Priority 3: Optional Templates (Consider for Future)

#### 6. FDO Version Update Template
**Rationale**: Tracking work for updating to new FDO releases.

**Purpose**: Create a master issue for coordinating all changes needed when updating FDO version.

**Template structure** (similar to new-arch.yml):
- Checklist for updating Makefile
- Checklist for updating Dockerfile
- Checklist for testing with new version
- Checklist for updating documentation
- Checklist for updating sample scripts

### Templates NOT Recommended

1. **new-arch.yml** - Not applicable (FDO-support doesn't build for multiple architectures)
2. **new-distro.yml** - Not applicable (Docker-based, distro-agnostic)
3. **user-feedback.yml** - Can use "Other.md" instead

## Implementation Structure

### Directory Structure
```
.github/
├── ISSUE_TEMPLATE/
│   ├── bug-report.yml
│   ├── feature_request.yml
│   ├── documentation-update.yml
│   ├── integration-issue.yml
│   ├── fdo-version-update.yml (optional)
│   ├── config.yml
│   └── Other.md
├── PULL_REQUEST_TEMPLATE.md
└── workflows/
    └── (existing workflows)
```

### config.yml Configuration

```yaml
blank_issues_enabled: false
contact_links:
  - name: Open Horizon Community Support
    url: https://github.com/open-horizon/open-horizon.github.io/discussions
    about: For general questions about Open Horizon
  - name: FDO Specification
    url: https://github.com/fido-device-onboard
    about: For questions about the FDO protocol itself
```

## Implementation Steps

### Phase 1: Core Templates (Week 1)

1. **Create .github/ISSUE_TEMPLATE directory**
   ```bash
   mkdir -p .github/ISSUE_TEMPLATE
   ```

2. **Implement bug-report.yml**
   - Copy from anax repository
   - Customize fields for FDO-support
   - Add FDO-specific environment fields
   - Test with a sample bug report

3. **Implement feature_request.yml**
   - Copy from anax repository
   - Customize description for FDO context
   - Test with a sample feature request

4. **Implement PULL_REQUEST_TEMPLATE.md**
   - Copy from anax repository
   - Add FDO-specific checklist items
   - Include DCO sign-off requirement
   - Test with a sample PR

5. **Create config.yml**
   - Disable blank issues
   - Add contact links for community support

### Phase 2: Documentation and Integration Templates (Week 2)

6. **Implement documentation-update.yml**
   - Copy from anax repository
   - Customize for FDO-support documentation structure
   - Test with a sample documentation issue

7. **Create integration-issue.yml**
   - Build custom template (see Priority 2 above)
   - Test with sample integration scenarios

8. **Create Other.md**
   - Simple markdown template for miscellaneous issues
   - Include guidance on choosing the right template

### Phase 3: Testing and Refinement (Week 3)

9. **Test all templates**
   - Create test issues using each template
   - Verify all fields render correctly
   - Check that labels are applied automatically
   - Ensure required fields are enforced

10. **Update AGENTS.md**
    - Document the new template structure
    - Add guidance for contributors on using templates

11. **Create announcement**
    - Update README.md with link to issue templates
    - Consider creating a GitHub Discussion post

### Phase 4: Optional Enhancements (Future)

12. **Implement fdo-version-update.yml** (if needed)
    - Create master issue template for FDO version updates
    - Include comprehensive checklist

13. **Add automation**
    - Consider GitHub Actions to auto-label issues
    - Auto-assign reviewers based on file paths
    - Auto-close stale issues

## Template Content Examples

### Bug Report Template (bug-report.yml)

```yaml
name: Bug Report
description: Report a bug in FDO-support
title: "Bug: "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report for FDO-support.
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: dropdown
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - OCS API
        - FDO Owner Services
        - Docker Container
        - Sample Manufacturing Scripts
        - Sample Rendezvous Scripts
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Set environment variables...
        2. Run command...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment Details
      description: |
        Please provide:
        - FDO Version (FIDO_DEVICE_ONBOARD_REL_VER)
        - FDO-support Version
        - Docker Version
        - Operating System
        - Go Version (if building from source)
      placeholder: |
        FDO Version: 1.1.10
        FDO-support Version: 1.12.0
        Docker Version: 24.0.0
        OS: Ubuntu 22.04
        Go Version: 1.21.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Configuration
      description: |
        Relevant environment variables (redact sensitive values):
        - HZN_EXCHANGE_URL
        - HZN_FSS_CSSURL
        - FDO_OWN_SVC_AUTH (redact password)
        - Any other relevant configuration
      placeholder: |
        HZN_EXCHANGE_URL=https://exchange.example.com
        HZN_FSS_CSSURL=https://css.example.com
        FDO_OWN_SVC_AUTH=apiUser:***
        VERBOSE=true

  - type: textarea
    attributes:
      label: Logs
      description: Relevant log output (from docker logs, OCS API, etc.)
      render: shell

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem

  - type: textarea
    attributes:
      label: Additional context
      description: Any other information that might be helpful
```

### Pull Request Template (PULL_REQUEST_TEMPLATE.md)

```markdown
## Description

Please include a summary of the changes and the related issue. Include relevant motivation and context.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] FDO version update
- [ ] Configuration change

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Tested with FDO-enabled device
- [ ] Tested with VM simulation (sample-mfg scripts)
- [ ] Tested voucher import/export
- [ ] Tested Exchange authentication
- [ ] Tested CSS file operations
- [ ] Tested Docker container build and run
- [ ] Tested agent installation on device

**Test Configuration**:
- FDO Version:
- Operating System:
- Docker Version:
- Test Environment (all-in-one, distributed, etc.):

## FDO-Specific Checklist

- [ ] Verified compatibility with current FDO specification version
- [ ] Tested with both HTTP and HTTPS configurations
- [ ] Updated API documentation if endpoints changed (docs/FDO-APIs.md)
- [ ] Updated usage documentation if workflow changed (docs/README-FDO.md)
- [ ] Verified Docker image builds successfully
- [ ] Tested TO0/TO1/TO2 protocol phases (if applicable)
- [ ] Verified Exchange authentication still works
- [ ] Tested with sample manufacturing scripts (if applicable)
- [ ] Checked certificate handling (if applicable)

## General Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published
- [ ] I have checked my code and corrected any misspellings
- [ ] I have tagged reviewers

## DCO Sign-Off

By submitting this pull request, I confirm that my contribution is made under the terms of the Developer Certificate of Origin (DCO).

- [ ] I have signed off my commits (`git commit -s`)
```

## Success Metrics

After implementation, measure success by:

1. **Adoption Rate**: Percentage of new issues using templates (target: >80%)
2. **Issue Quality**: Reduction in "needs more information" labels (target: 30% reduction)
3. **Time to Resolution**: Faster issue resolution due to better initial information
4. **PR Quality**: Fewer review cycles needed due to comprehensive checklist
5. **Community Feedback**: Positive feedback from contributors

## Maintenance Plan

- **Quarterly Review**: Review template effectiveness and update as needed
- **FDO Version Updates**: Update templates when FDO specification changes
- **Community Input**: Solicit feedback from contributors on template usefulness
- **Continuous Improvement**: Refine templates based on actual usage patterns

## References

- [GitHub Issue Forms Documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
- [open-horizon/anax Templates](https://github.com/open-horizon/anax/tree/master/.github/ISSUE_TEMPLATE)
- [FDO Specification](https://github.com/fido-device-onboard)
- [Open Horizon Documentation](https://open-horizon.github.io/)

## Appendix: Template Comparison Matrix

| Template | Anax | FDO-support | Customization Level | Priority |
|----------|------|-------------|---------------------|----------|
| Bug Report | ✅ | ✅ | High | P1 |
| Feature Request | ✅ | ✅ | Medium | P1 |
| Documentation Update | ✅ | ✅ | Medium | P2 |
| Pull Request | ✅ | ✅ | High | P1 |
| Integration Issue | ❌ | ✅ | New | P2 |
| FDO Version Update | ❌ | ✅ | New | P3 |
| New Architecture | ✅ | ❌ | N/A | N/A |
| New Distro | ✅ | ❌ | N/A | N/A |
| User Feedback | ✅ | ❌ | N/A | N/A |
| Other | ✅ | ✅ | Low | P2 |

---

**Document Version**: 1.0  
**Last Updated**: March 11, 2026  
**Author**: Development Team  
**Status**: Ready for Implementation

@t-fine Here's Bob's plan for templates.  Any feedback before I begin implementing?
